In [1]:
import numpy as np
from matplotlib import pyplot as plt

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
A = np.array([[0.5,0.5,0.25],[0.25,0,0.25],[0.25,0.5,0.5]])

In [7]:
xtoday = np.array([[1.0],[0.0],[0.0]])

In [8]:
for k in range(49):
    xtomorrow = A * xtoday
    print(k)
    print(xtomorrow)
    xtoday = xtomorrow

0
[[0.5  0.5  0.25]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
1
[[0.25   0.25   0.0625]
 [0.     0.     0.    ]
 [0.     0.     0.    ]]
2
[[0.125    0.125    0.015625]
 [0.       0.       0.      ]
 [0.       0.       0.      ]]
3
[[0.0625     0.0625     0.00390625]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
4
[[0.03125    0.03125    0.00097656]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
5
[[0.015625   0.015625   0.00024414]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
6
[[7.81250000e-03 7.81250000e-03 6.10351562e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
7
[[3.90625000e-03 3.90625000e-03 1.52587891e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
8
[[1.95312500e-03 1.95312500e-03 3.81469727e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]
9